# Generated by Django 3.0.2 on 2020-01-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('is_gluten_free', models.BooleanField()),
                ('is_vegan', models.BooleanField()),
                ('is_organic', models.BooleanField()),
                ('product_stock', models.IntegerField(null=True)),
                ('is_special', models.BooleanField()),
                ('product_price_dolar', models.FloatField(null=True)),
                ('product_price_bolivares', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(max_length=100)),
                ('client_cedula', models.IntegerField(null=True)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClientType')),
            ],
        ),
    ]
