# Generated by Django 3.0.2 on 2020-02-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_birthday',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
