# Generated by Django 3.0.3 on 2020-02-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zona',
            new_name='Zone',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='zona',
            new_name='zone',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='zona_name',
            new_name='zone_name',
        ),
    ]
