# Generated by Django 3.0.3 on 2020-02-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_client_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_sub_total', models.FloatField()),
                ('bill_total', models.FloatField()),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('bill_time', models.TimeField(auto_now_add=True)),
                ('bill_sale', models.FloatField()),
                ('bill_delivery', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_last_name', models.CharField(max_length=30)),
                ('employee_cedula', models.IntegerField(unique=True)),
                ('employee_gender', models.CharField(choices=[('F', 'Femenine'), ('M', 'Masculine')], max_length=1)),
                ('employee_birth_date', models.DateField()),
                ('employee_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_status', models.CharField(choices=[('Entregado', 'Entregado'), ('No Entregado', 'No Entregado')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_plate', models.CharField(max_length=7)),
                ('transport_model', models.CharField(max_length=30)),
                ('transport_brand', models.CharField(choices=[('TOYOTA', 'TOYOTA'), ('FORD', 'FORD'), ('HONDA', 'HONDA')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='units_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_gender',
            field=models.CharField(choices=[('F', 'Femenine'), ('M', 'Masculine')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='type_of_product',
            name='type',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, null=True)),
                ('open_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('store_phone', models.IntegerField(unique=True)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Zona')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField()),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.FloatField()),
                ('delivery_status', models.CharField(choices=[('Entregado', 'Entregado'), ('No Entregado', 'No Entregado')], max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Zona')),
            ],
        ),
        migrations.CreateModel(
            name='CashRegisterIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_income_total', models.FloatField()),
                ('income_date', models.DateField(auto_now_add=True)),
                ('cash_register_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CashRegister')),
            ],
        ),
        migrations.AddField(
            model_name='cashregister',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bill')),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
    ]
