# Generated by Django 3.0.3 on 2020-02-22 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200205_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('payment_method_instrument', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_total',
        ),
        migrations.AddField(
            model_name='batch',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
        migrations.AddField(
            model_name='bill',
            name='cash_register_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.CashRegister'),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='product_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='bill_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Bill'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickup',
            name='bill_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Bill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_iva',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.IVA'),
        ),
    ]
