# Generated by Django 3.0.2 on 2020-01-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200128_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_points', models.IntegerField(default=0)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_birthday', models.DateField()),
                ('member_start_date', models.DateField()),
                ('member_end_date', models.DateField()),
                ('member_gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientType2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.AddField(
            model_name='member_client',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AddField(
            model_name='member_client',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
    ]
