# Generated by Django 3.0.2 on 2020-01-28 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200128_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='client_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Member_Client',
        ),
    ]
