# Generated by Django 3.0.2 on 2020-01-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200128_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='client_id',
        ),
        migrations.CreateModel(
            name='Member_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
    ]
