# Generated by Django 3.0.2 on 2020-01-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200128_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
            preserve_default=False,
        ),
    ]
