# Generated by Django 3.0.2 on 2020-01-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200128_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_stock',
        ),
    ]
